In [1]:
import numpy

# A = numpy.random.randn(5, 5)
# B = numpy.random.randn(5, 5)
A = numpy.array([
    [1, 6, 4, 3, 0],
    [4, 1, 3, 0, 0],
    [5, 0, 0, 1, 0],
    [0, 0, 0, 0, 0],
    [1, 1, 3, 6, 8]
])
B = numpy.array([
    [1, 2, 4, 7, 0],
    [0, 1, 1, 8, 0],
    [2, 4, 0, 9, 0],
    [1, 2, 6, 5, 8],
    [2, 4, 0, 2, 1]
])


# A、B 每行的和


In [2]:
print(A.sum(axis=1))
print(B.sum(axis=1))

[14  8  6  0 19]
[14 10 15 22  9]


# A、B 每列的和

In [3]:
print(A.sum(axis=0))
print(A.sum(axis=0))

[11  8 10 10  8]
[11  8 10 10  8]


# A、B 所有元素的和

In [4]:
print(A.sum())
print(B.sum())

47
70


# A矩阵元素除以该A矩阵所有元素和，输出得到的矩阵

In [5]:
sumOfA = A.sum()
AA = numpy.array(A, dtype=float)
print(AA/sumOfA)

[[0.0212766  0.12765957 0.08510638 0.06382979 0.        ]
 [0.08510638 0.0212766  0.06382979 0.         0.        ]
 [0.10638298 0.         0.         0.0212766  0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.0212766  0.0212766  0.06382979 0.12765957 0.17021277]]


# 矩阵存入名为“normalization.txt”文件中

In [6]:
numpy.savetxt('normalization.txt', AA)

# 输出A、B矩阵相乘矩阵的形状

In [7]:
AdotB = numpy.dot(A, B)
print(AdotB.shape)

(5, 5)


# 矩阵存入名为“multiply.txt”文件中

In [8]:
numpy.savetxt('multiply.txt', AdotB)

# 输出A的转置

In [9]:
At = numpy.transpose(A)
print(At)

[[1 4 5 0 1]
 [6 1 0 0 1]
 [4 3 0 0 3]
 [3 0 1 0 6]
 [0 0 0 0 8]]


# 计算A、B的和

In [10]:
sumOfAB = A+B
print(sumOfAB)

[[ 2  8  8 10  0]
 [ 4  2  4  8  0]
 [ 7  4  0 10  0]
 [ 1  2  6  5  8]
 [ 3  5  3  8  9]]
